services:
  - type: web
    name: finance-manager-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn finance_manager_app.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: finance_manager_app.settings
      - key: DEBUG
        value: False
      - fromDotEnv: true
